# Generated by Django 4.1.3 on 2022-11-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blogcategorymodel_blogcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя категории'),
        ),
    ]
