# Generated by Django 4.1.4 on 2022-12-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_alter_blogcategory_options_article_text_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='img',
        ),
    ]
