# Generated by Django 4.1.4 on 2023-02-28 16:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_description_alter_category_image_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Зміст'),
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активовано')),
                ('products', models.ManyToManyField(to='catalog.product', verbose_name='Продукти')),
            ],
            options={
                'verbose_name': 'Карусель товару',
                'verbose_name_plural': 'Карусель товарів',
                'ordering': ['sort'],
            },
        ),
    ]
