# Generated by Django 4.1.4 on 2023-02-21 15:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активировано'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=tinymce.models.HTMLField(null=True, verbose_name='Описание'),
        ),
    ]
